# Generated by Django 4.2 on 2024-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_verify',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TokenVerification'),
        ),
    ]
