# Generated by Django 4.2 on 2024-06-13 21:54

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_course/', verbose_name='Фотография курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
