# Generated by Django 4.2 on 2024-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='coursecardmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_course/', verbose_name='Фотография курса'),
        ),
    ]
