# Generated by Django 4.2 on 2024-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_user_photo_alter_coursecardmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecardmodel',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='coursecardmodel',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
