# Generated by Django 4.2 on 2024-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coursecardmodel_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bought_course',
            field=models.ManyToManyField(blank=True, to='main.coursecardmodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
